spring:
  application:
    name: libraryapi
  #Criando conexão com o banco de dados PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver #Conecta nossa aplicação ao banco de dados
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update #Atualiza o banco automaticamente
    properties:
      hibernate.format_sql: true

