spring:
  application:
    name: libraryapi
#  profiles:
#    active: development
  output:
    ansi:
      enabled: ALWAYS
  #Criando conexão com o banco de dados PostgreSQL
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/library}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver #Conecta nossa aplicação ao banco de dados
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: update #Atualiza o banco automaticamente
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

springdoc:
  #Remove respostas geneéricas do Swagger
  override-with-generic-response: false

logging:
  file:
    name: app.log
  level:
    root: warn
    io:
      github:
        websterrodrigues: debug
    org:
      springframework:
        web: warn

# trace
# debug
# info
# warn
# error


management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'

#Production
---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false

#Staging
---
spring:
  config:
    activate:
      on-profile: homological
  jpa:
    show-sql: false

#Development
---
spring:
  config:
    activate:
      on-profile: development
